# Generated by Django 3.2.5 on 2021-07-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=64)),
                ('car_model', models.CharField(max_length=64)),
                ('engine', models.IntegerField()),
                ('fuel', models.IntegerField(choices=[(1, 'Benzyna'), (2, 'Deisel'), (3, 'Benzyna+LPG'), (4, 'Elektryczne')])),
                ('vintage', models.IntegerField()),
                ('course', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone_number', models.IntegerField()),
                ('address', models.CharField(max_length=64)),
                ('note', models.IntegerField(choices=[(1, 'słaby'), (2, 'przeciętny'), (3, 'średni'), (4, 'dobry'), (5, 'bardzo dobry')])),
                ('prices', models.IntegerField(choices=[(1, 'tani'), (2, 'średni'), (3, 'drogi')])),
                ('short_description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'silnik'), (2, 'zawieszenie'), (3, 'elektryka'), (4, 'wulkanizacja'), (5, 'wymianny okresowe'), (6, 'inne')])),
                ('description', models.CharField(max_length=1000)),
                ('date_repair', models.DateTimeField(auto_now_add=True)),
                ('cost', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_check.car')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_check.workshop')),
            ],
        ),
        migrations.CreateModel(
            name='Remainder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_check.car')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('car', models.ManyToManyField(to='car_check.Car')),
            ],
        ),
    ]
